service: my-serverless-app

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    MERCADOPAGO_ACCESS_TOKEN: ${env:MERCADOPAGO_ACCESS_TOKEN}
    RESEND_API_KEY: ${env:RESEND_API_KEY}
    RESEND_FROM_EMAIL: ${env:RESEND_FROM_EMAIL}

functions:
  hello:
    handler: src/handlers/index.hello
    events:
      - http:
          path: hello
          method: get

  getEvents:
    handler: src/handlers/events.getEvents
    events:
      - http:
          path: events
          method: get

  getEvent:
    handler: src/handlers/events.getEvent
    events:
      - http:
          path: events/{id}
          method: get

  createEvent:
    handler: src/handlers/events.createEvent
    events:
      - http:
          path: events
          method: post

  addLotes:
    handler: src/handlers/events.addLotes
    events:
      - http:
          path: events/{id}/lotes
          method: put

  createOrder:
    handler: src/handlers/orders.default
    events:
      - http:
          path: orders
          method: post

  webhook:
    handler: src/handlers/webhook.default
    events:
      - http:
          path: webhook
          method: post

plugins:
  - serverless-offline

package:
  individually: false
  patterns:
    - generated/prisma/**

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    format: esm
    platform: node
    external:
      - pg  
      - pg/*
      - '@prisma/client'
      - '.prisma/client'
      - '../generated/prisma/*'